# Site settings
title: Proyectos de Martin Ribelotta
email: martinribelotta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sitio simple, estático y totalmente poco llamativo, porque lo que importa
  es la cerveza... digo, el contenido...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martinribelotta.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  martinribelotta

# Build settings
markdown: kramdown
